-- 음식점 테이블
CREATE TABLE RESTAURANT (
    RESTAURANT_ID     NUMBER(10)       NOT NULL,  -- PK
    RESTAURANT_NAME   VARCHAR2(100)    NULL,      -- 음식점 이름
    RESTAURANT_ADDRESS VARCHAR2(255)   NOT NULL,  -- 음식점 주소
    RESTAURANT_PHONE  VARCHAR2(50)     NOT NULL,  -- 음식점 전화번호
    CONSTRAINT PK_RESTAURANT PRIMARY KEY (RESTAURANT_ID)
);

-- 메뉴 테이블
CREATE TABLE MENU (
    MENU_ID       NUMBER(10)       NOT NULL,  -- PK
    MENU_NAME     VARCHAR2(100)    NULL,      -- 메뉴 이름
    MENU_PRICE    NUMBER(10)       NULL,      -- 가격
    RESTAURANT_ID NUMBER(10)       NOT NULL,  -- FK
    CONSTRAINT PK_MENU PRIMARY KEY (MENU_ID),
    CONSTRAINT FK_MENU_RESTAURANT FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANT (RESTAURANT_ID)
);

-- 주문 테이블
CREATE TABLE ORDERS (
    ORDER_ID        NUMBER(10)       NOT NULL, -- PK
    MEMBER_ID       VARCHAR2(50)     NULL,     -- 주문 회원 ID
    DELIVERY_ADDRESS VARCHAR2(255)   NULL,     -- 배달 주소
    REQUEST_NOTE    VARCHAR2(255)    NULL,     -- 주문 요청사항
    TOTAL_AMOUNT    NUMBER(10)       NULL,     -- 총 결제 금액
    ORDER_TYPE      VARCHAR2(10)     NULL,     -- 주문 방식 (배달/포장)
    PAYMENT_STATUS  CHAR(1)          NULL,     -- 결제 여부 (Y/N)
    ORDER_TIME      DATE             NULL,     -- 주문 시간
    RESTAURANT_ID   NUMBER(10)       NOT NULL, -- FK
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_RESTAURANT FOREIGN KEY (RESTAURANT_ID)
        REFERENCES RESTAURANT (RESTAURANT_ID)
);

-- 주문-메뉴 연결 테이블 (복합 PK)
CREATE TABLE ORDER_MENU (
    QUANTITY    NUMBER(5)       NULL,         -- 수량
    MENU_ID     NUMBER(10)      NOT NULL,     -- FK, PK
    ORDER_ID    NUMBER(10)      NOT NULL,     -- FK, PK
    CONSTRAINT PK_ORDER_MENU PRIMARY KEY (MENU_ID, ORDER_ID),
    CONSTRAINT FK_ORDER_MENU_MENU FOREIGN KEY (MENU_ID)
        REFERENCES MENU (MENU_ID),
    CONSTRAINT FK_ORDER_MENU_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID)
);
