-- 기존 것 있으면 정리(선택)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_MENU CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MENU CASCADE CONSTRAINTS';       EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESTAURANT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1) 음식점
CREATE TABLE RESTAURANT (
  RESTAURANT_ID       NUMBER(10)    NOT NULL,
  RESTAURANT_NAME     VARCHAR2(100),
  RESTAURANT_ADDRESS  VARCHAR2(255) NOT NULL,
  RESTAURANT_PHONE    VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_RESTAURANT PRIMARY KEY (RESTAURANT_ID)
);

-- 2) 메뉴 (음식점별 소속)
CREATE TABLE MENU (
  MENU_ID        NUMBER(10)    NOT NULL,
  MENU_NAME      VARCHAR2(100),
  MENU_PRICE     NUMBER(10),
  RESTAURANT_ID  NUMBER(10)    NOT NULL,
  CONSTRAINT PK_MENU PRIMARY KEY (MENU_ID),
  CONSTRAINT FK_MENU_RESTAURANT FOREIGN KEY (RESTAURANT_ID)
    REFERENCES RESTAURANT (RESTAURANT_ID)
);

-- 3) 주문
CREATE TABLE ORDERS (
  ORDER_ID         NUMBER(10)     NOT NULL,
  MEMBER_ID        VARCHAR2(50),
  DELIVERY_ADDRESS VARCHAR2(255),
  REQUEST_NOTE     VARCHAR2(255),
  TOTAL_AMOUNT     NUMBER(10),
  ORDER_TYPE       VARCHAR2(12),
  PAYMENT_STATUS   CHAR(1),
  ORDER_TIME       DATE,
  RESTAURANT_ID    NUMBER(10)     NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
  CONSTRAINT FK_ORDERS_RESTAURANT FOREIGN KEY (RESTAURANT_ID)
    REFERENCES RESTAURANT (RESTAURANT_ID),
  CONSTRAINT CK_ORDERS_TYPE CHECK (ORDER_TYPE IN ('배달','포장')),
  CONSTRAINT CK_ORDERS_PAY_YN CHECK (PAYMENT_STATUS IN ('Y','N'))
);

-- 4) 주문-메뉴(주문 상세)
CREATE TABLE ORDER_MENU (
  ORDER_ID  NUMBER(10) NOT NULL,
  MENU_ID   NUMBER(10) NOT NULL,
  QUANTITY  NUMBER(5),
  CONSTRAINT PK_ORDER_MENU PRIMARY KEY (ORDER_ID, MENU_ID),
  CONSTRAINT FK_ORDER_MENU_ORDER FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS (ORDER_ID),
  CONSTRAINT FK_ORDER_MENU_MENU  FOREIGN KEY (MENU_ID)
    REFERENCES MENU (MENU_ID)
);

-- 조인/삭제 성능을 위한 FK 인덱스(옵션)
CREATE INDEX IX_MENU_RESTAURANT_ID   ON MENU(RESTAURANT_ID);
CREATE INDEX IX_ORDERS_RESTAURANT_ID ON ORDERS(RESTAURANT_ID);


