SELECT 
    o.ORDER_ID,
    o.MEMBER_ID,
    r.RESTAURANT_NAME,
    o.DELIVERY_ADDRESS,
    o.REQUEST_NOTE,
    m.MENU_NAME,
    m.MENU_PRICE,
    om.QUANTITY,
    (m.MENU_PRICE * om.QUANTITY) AS ITEM_TOTAL,
    o.TOTAL_AMOUNT,
    o.ORDER_TYPE,
    o.PAYMENT_STATUS,
    o.ORDER_TIME
FROM ORDERS o
JOIN RESTAURANT r 
    ON o.RESTAURANT_ID = r.RESTAURANT_ID
JOIN ORDER_MENU om
    ON o.ORDER_ID = om.ORDER_ID
JOIN MENU m
    ON om.MENU_ID = m.MENU_ID
WHERE o.ORDER_ID = 1;
