CREATE TABLE "MENU" (
	"PK"	NUMBER(10)		NULL,
	"Field1"	VARCHAR2(100)		NULL,
	"Field2"	NUMBER(10)		NULL,
	"FK1"	NUMBER(10)		NOT NULL
);

CREATE TABLE "RESTAURANT" (
	"PK"	NUMBER(10)		NOT NULL,
	"Field1"	VARCHAR2(100)		NULL,
	"Field2"	VARCHAR2(255)		NOT NULL,
	"Field3"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "ORDERS" (
	"PK"	NUMBER(10)		NOT NULL,
	"Field1"	VARCHAR2(50)		NULL,
	"Field2"	varchar2(255)		NULL,
	"Field3"	VARCHAR2(255)		NULL,
	"Field4"	NUMBER(10)		NULL,
	"Field5"	VARCHAR2(10)		NULL,
	"Field6"	CHAR(1)		NULL,
	"Field7"	DATE		NULL,
	"FK1"	NUMBER(10)		NOT NULL
);

CREATE TABLE "ORDER_MENU" (
	"Field1"	NUMBER(5)		NULL,
	"FK2"	NUMBER(10)		NULL,
	"PK,FK1"	NUMBER(10)		NOT NULL
);

ALTER TABLE "MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY (
	"PK"
);

ALTER TABLE "RESTAURANT" ADD CONSTRAINT "PK_RESTAURANT" PRIMARY KEY (
	"PK"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY (
	"PK"
);

